---
- name: Collect /data filesystem information
  hosts: servers

  tasks:
    - name: Get /data filesystem information
      ansible.builtin.command: df -Th /data
      register: data_usage
      changed_when: false
      check_mode: false

    - name: Store filesystem information
      ansible.builtin.set_fact:
        filesystem_info:
          server: "{{ inventory_hostname }}"
          total: "{{ data_usage.stdout.split('\n')[1].split()[2] }}"
          used: "{{ data_usage.stdout.split('\n')[1].split()[3] }}"
          available: "{{ data_usage.stdout.split('\n')[1].split()[4] }}"
          utilization: "{{ data_usage.stdout.split('\n')[1].split()[5] }}"

    - name: Generate filesystem usage report
      ansible.builtin.template:
        src: "../templates/usage_report.txt.j2"
        dest: "../../reports/usage_report_{{ now(fmt='%Y%m%d_%H%M%S') }}.txt"
      delegate_to: localhost
      run_once: true
